### ISSUE TITLE
Segfault !

### ISSUE THREAD

**Issue by Ne02ptzero** [Ne02ptzero/rogue-like#9]
J'ai un segfault quand je ramasse 2 fois la meme arme (J'ai un arc equipe, et un arc tombe d'un monstre):

```
Program received signal SIGSEGV, Segmentation fault.
0x0817022a in b2World::DestroyBody(b2Body*) ()
```

```
(gdb) bt
#0  0x0817022a in b2World::DestroyBody(b2Body*) ()
#1  0x08057509 in Game::destroyAllBodies () at Sources/src/Game.cpp:218
#2  0x08112898 in World::TickAndRender (this=0x82bd840) at Infrastructure/World.cpp:651
#3  0x08111a4e in World::StartGame (this=0x82bd840) at Infrastructure/World.cpp:428
```

Peut etre que l'arme par terre est le meme objet que celle equipe ?

**Comment by N0ich** [comment]
Bug fixed 
CF [ce commit](https://github.com/Ne02ptzero/rogue-like/commit/16852b94a86b0b10fd1cf43b6b5e4df6ad2cf565)
